### ISSUE TITLE
CSS 面试

### ISSUE THREAD

**Issue by ChelesteWang** [ChelesteWang/FE-Review#37]
## CSS 画三角
原理：border 属性绘制的边框为梯形,只保留一面其他的颜色都设置为`transparent`透明
```css
span {
    width: 0;
    height: 0;
    border-top: 40px solid transparent;
    border-left: 40px solid transparent;
    border-right: 40px solid transparent;
    border-bottom: 40px solid #ff0000;
}
```
